#!/usr/bin/env bash
# Render <name>.dot -> <name>.svg + <name>.png, where <name> is this script's
# own basename. Copy the script under a new name to render another .dot.
# Run from anywhere; outputs land next to the .dot. Requires GraphViz `dot`
# and `rsvg-convert` (librsvg) for the PNG.
#   ./concept.sh            # 200 dpi PNG
#   ./concept.sh 140        # custom PNG dpi
set -euo pipefail

here="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
stem="$here/$(basename "${BASH_SOURCE[0]}" .sh)"
dpi="${1:-200}"

command -v dot >/dev/null || { echo "dot (GraphViz) not found on PATH" >&2; exit 1; }
[[ -f "$stem.dot" ]]     || { echo "missing $stem.dot" >&2; exit 1; }

# dot's node order within a rank is not stable across GraphViz versions in
# rankdir=LR; if the existing SVG came from another version, check the row
# order (see the comments in the .dot) before committing.
have="$(dot -V 2>&1 | sed -E 's/^dot - graphviz version ([^ ]+).*/\1/')"
want=""   # first render: no SVG yet (a sed on a missing file would trip pipefail)
[[ -f "$stem.svg" ]] && want="$(sed -nE 's/^<!-- Generated by graphviz version ([^ ]+).*/\1/p' "$stem.svg" | head -1)"
[[ -n "$want" && "$want" != "$have" ]] && \
  echo "warning: $stem.svg was last rendered by graphviz $want, local dot is $have; layout may differ" >&2

dot -Tsvg "$stem.dot" -o "$stem.svg"
if command -v rsvg-convert >/dev/null; then
  # PNG from the finished SVG (dot's own PNG writer clips edge labels);
  # zoom = dpi / 72 keeps the SVG's point size.
  rsvg-convert -z "$(awk "BEGIN { print $dpi / 72 }")" "$stem.svg" -o "$stem.png"
  echo "rendered $stem.svg and $stem.png (${dpi} dpi)"
else
  echo "rendered $stem.svg (rsvg-convert not found: PNG skipped)"
fi
